Update run

diff --git a/s6-services/dbus-daemon/run b/s6-services/dbus-daemon/run
--- a/s6-services/dbus-daemon/run
+++ b/s6-services/dbus-daemon/run
@@ -1,5 +1,6 @@
 #!/bin/bash
-if [  ! -d /var/run/dbus ]; then
-  mkdir -p /var/run/dbus
+if [  ! -f /run/dbus/system_bus_socket ]; then
+  echo "dbus-daemon error. Ensure dbus-daemon is running in the host system and that /run/dbus is mounted. Exiting"
+  exit 1
 fi
 dbus-daemon --system --print-address --nofork
